# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TeamFinderApp

on:
  push:
    branches:
      - add-docker
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0d8399624bf34cab9174d7a246554c57 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6e6b9e5e7b0345fbb6aeb356e7aba6da }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0d8399624bf34cab9174d7a246554c57 }}/igorcroitoru/teamfinderapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TeamFinderApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b261939e8fcb4e158cf9319a1c0d3055 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0d8399624bf34cab9174d7a246554c57 }}/igorcroitoru/teamfinderapp:${{ github.sha }}'